name: "白泽"
mode: "dev"
port: 8080
version: "v1.0.3"
start_time: "2021-05-07"
machine_id: 1
profile: "./uploadPath"
log:
  level: "info"
  filename: "./baizelog.log"
  max_size: 200
  max_age: 30
  max_backups: 7
mysql:
  host: 172.16.0.2
  port: 3306
  user: "root"
  password: "Ab123145"
  dbname: "db_ruoyi"
  max_open_conns: 32
  max_idle_conns: 16
redis:
  host: 172.16.0.2
  port: 6379
  password: "Ab123145"
  db: 0
  pool_size: 100
token:
  expireTime: 30
  secret: abcdefghijklmnopqrstuvwxyz
  issuer: baize
